// Legal texts copied verbatim from wearesanctum.com (terms-conditions, privacy-policy).
// Format: lines starting with "## " are section headings; blank lines separate paragraphs.
export const terms = `TERMS OF SERVICE

THIS TERMS OF SERVICE AGREEMENT (THIS “AGREEMENT” OR THESE “TERMS”) IS A LEGAL AGREEMENT BETWEEN YOU, ON THE ONE HAND (“YOU,” “YOUR,” “USER”), AND SANCTUM B.V., A PRIVATE LIMITED LIABILITY COMPANY INCORPORATED UNDER THE LAWS OF THE NETHERLANDS, WITH ITS REGISTERED OFFICE AT SINGEL 174A, 1016 AJ AMSTERDAM, THE NETHERLANDS (THE “COMPANY,” “SANCTUM,” “WE,” “US,” OR “OUR”), ON THE OTHER HAND, REGARDING YOUR ACCESS TO AND USE OF THE SERVICES (AS DEFINED BELOW).

THE “SERVICES” INCLUDE, WITHOUT LIMITATION: (I) ANY IN-PERSON CLASSES, EXPERIENCES, PROGRAMS, EVENTS, WORKSHOPS, RETREATS, ACTIVATIONS, OR ACTIVITIES HOSTED, SPONSORED, OPERATED, LICENSED, OR OTHERWISE AFFILIATED WITH SANCTUM (COLLECTIVELY, THE “IN-PERSON SERVICES”); (II) ANY DIGITAL, ONLINE, OR ON-DEMAND CONTENT, INCLUDING AUDIO, VIDEO, LIVESTREAMS, AND WRITTEN MATERIALS (COLLECTIVELY, THE “DIGITAL SERVICES”); (III) ANY WEBSITE(S) OPERATED BY OR FOR SANCTUM, INCLUDING WWW.WEARESANCTUM.COM (THE “WEBSITE”); (IV) ANY MOBILE APPLICATION(S), DOWNLOADABLE SOFTWARE, OR DIGITAL PLATFORM(S) PROVIDED BY SANCTUM NOW OR IN THE FUTURE (COLLECTIVELY, THE “APP”); AND (V) ANY RELATED BOOKINGS, MEMBERSHIPS, SUBSCRIPTIONS, COMMUNICATIONS, SUPPORT, OR OTHER FEATURES MADE AVAILABLE BY SANCTUM (TOGETHER WITH THE IN-PERSON SERVICES, DIGITAL SERVICES, WEBSITE, AND APP, THE “SERVICE”).

BY CLICKING “I AGREE,” “I ACCEPT,” OR EQUIVALENT LANGUAGE, BY CREATING AN ACCOUNT, BY PURCHASING OR USING ANY PORTION OF THE SERVICE, OR BY OTHERWISE ACCESSING OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS AGREEMENT IN ALL RESPECTS. YOU FURTHER ACKNOWLEDGE THAT THIS AGREEMENT CONTAINS A RELEASE OF LIABILITY, WAIVER OF CLAIMS, ASSUMPTION OF RISKS, LIMITATION OF LIABILITY, AND INDEMNITY PROVISIONS THAT AFFECT YOUR LEGAL RIGHTS, INCLUDING, WITHOUT LIMITATION, YOUR RIGHT TO SUE.

## PART 1: RELEASE OF LIABILITY, WAIVER OF CLAIMS, ASSUMPTION OF RISKS, AND INDEMNITY

PLEASE READ CAREFULLY. IN CONSIDERATION OF SANCTUM PERMITTING YOU TO ACCESS AND USE THE SERVICE, AND FOR OTHER GOOD AND VALUABLE CONSIDERATION, THE RECEIPT AND SUFFICIENCY OF WHICH ARE HEREBY ACKNOWLEDGED, YOU AGREE AS FOLLOWS:

## 1. ASSUMPTION OF RISKS (IN-PERSON SERVICES)

1.1 YOU ACKNOWLEDGE AND UNDERSTAND THAT THE IN-PERSON SERVICES MAY INVOLVE RISKS, DANGERS, AND HAZARDS, INCLUDING WITHOUT LIMITATION THE RISK OF SERIOUS INJURY, PERMANENT DISABILITY, DEATH, PROPERTY LOSS OR DAMAGE, AND/OR EMOTIONAL OR PSYCHOLOGICAL DISTRESS.

1.2 YOU ACKNOWLEDGE THAT YOU ARE VOLUNTARILY PARTICIPATING IN THE IN-PERSON SERVICES AND YOU FREELY ACCEPT AND FULLY ASSUME ANY AND ALL RISKS, DANGERS, AND HAZARDS ASSOCIATED WITH SUCH PARTICIPATION, WHETHER CAUSED BY THE NEGLIGENCE OF SANCTUM OR OTHERWISE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.

1.3 YOU ACKNOWLEDGE THAT SANCTUM MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE SAFETY OR OUTCOMES OF PARTICIPATION AND THAT INDIVIDUAL EXPERIENCES VARY.

## 2. DIGITAL SERVICES DISCLAIMER; NO MEDICAL ADVICE

2.1 YOU ACKNOWLEDGE AND AGREE THAT THE DIGITAL SERVICES (INCLUDING CONTENT PROVIDED THROUGH THE APP) ARE PROVIDED FOR INFORMATIONAL AND EXPERIENTIAL PURPOSES ONLY.

2.2 THE SERVICE DOES NOT PROVIDE MEDICAL, PSYCHOLOGICAL, PSYCHIATRIC, THERAPEUTIC, OR OTHER PROFESSIONAL ADVICE, AND IS NOT A SUBSTITUTE FOR SUCH ADVICE. NO PRACTITIONER-CLIENT, THERAPIST-PATIENT, OR OTHER FIDUCIARY RELATIONSHIP IS CREATED.

2.3 YOU ACKNOWLEDGE THAT YOU SHOULD CONSULT A QUALIFIED HEALTHCARE PROFESSIONAL BEFORE PARTICIPATING IN ANY PHYSICAL OR WELLNESS PRACTICE, INCLUDING ANY PRACTICE ACCESSED THROUGH THE SERVICE.

## 3. HEALTH REPRESENTATIONS AND FITNESS TO PARTICIPATE

3.1 YOU REPRESENT AND WARRANT THAT YOU ARE IN GOOD PHYSICAL AND MENTAL CONDITION AND THAT YOU HAVE NO MEDICAL OR PHYSICAL CONDITION THAT WOULD PREVENT YOUR SAFE PARTICIPATION IN THE SERVICE.

3.2 IF YOU ARE PREGNANT, INJURED, RECOVERING FROM ILLNESS, HAVE A HEART CONDITION OR OTHER CHRONIC CONDITION, HAVE A HISTORY OF SEIZURES OR PHOTOSENSITIVITY, OR OTHERWISE HAVE HEALTH CONCERNS, YOU AGREE TO CONSULT A MEDICAL PROFESSIONAL PRIOR TO PARTICIPATION AND TO MODIFY OR DISCONTINUE PARTICIPATION IMMEDIATELY IF YOU EXPERIENCE ANY DISCOMFORT, DIZZINESS, PAIN, OR DISTRESS.

3.3 SANCTUM RESERVES THE RIGHT, IN ITS SOLE DISCRETION, TO REFUSE OR DISCONTINUE YOUR PARTICIPATION IF SANCTUM DETERMINES THAT YOUR PARTICIPATION MAY POSE A RISK TO YOUR HEALTH OR SAFETY OR THE HEALTH OR SAFETY OF OTHERS.

## 4. COMPLIANCE WITH INSTRUCTIONS; SAFE CONDUCT

4.1 YOU AGREE TO COMPLY AT ALL TIMES WITH ALL POSTED RULES, SAFETY INSTRUCTIONS, AND ANY VERBAL GUIDANCE PROVIDED BY SANCTUM STAFF, FACILITATORS, OR PARTNERS.

4.2 IF YOU OBSERVE ANY HAZARD, YOU AGREE TO NOTIFY SANCTUM IMMEDIATELY. FAILURE TO FOLLOW INSTRUCTIONS MAY RESULT IN REMOVAL FROM THE EXPERIENCE WITHOUT REFUND.

4.3 YOU AGREE NOT TO PARTICIPATE WHILE UNDER THE INFLUENCE OF DRUGS OR ALCOHOL AND TO CONDUCT YOURSELF IN A SAFE AND REASONABLE MANNER AT ALL TIMES.

## 5. RELEASE AND WAIVER OF CLAIMS

5.1 YOU HEREBY EXPRESSLY WAIVE, RELEASE, AND DISCHARGE ANY AND ALL CLAIMS YOU HAVE OR MAY IN THE FUTURE HAVE AGAINST SANCTUM AND ITS AFFILIATES, AND EACH OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, INSTRUCTORS, CONTRACTORS, AGENTS, REPRESENTATIVES, SHAREHOLDERS, SUCCESSORS, ASSIGNS, AND PARTNERS (COLLECTIVELY, THE “RELEASEES”), ARISING OUT OF OR RELATING TO THE SERVICE, INCLUDING WITHOUT LIMITATION ANY CLAIMS ARISING FROM OR RELATING TO (I) PARTICIPATION IN THE IN-PERSON SERVICES; (II) USE OF THE DIGITAL SERVICES; (III) USE OF ANY VENUE OR FACILITY; (IV) ANY ACTS OR OMISSIONS OF ANY RELEASEE; OR (V) ANY THIRD-PARTY SERVICES OR LOCATIONS, IN EACH CASE DUE TO ANY CAUSE WHATSOEVER, INCLUDING WITHOUT LIMITATION NEGLIGENCE, BREACH OF CONTRACT, OR BREACH OF ANY STATUTORY OR OTHER DUTY OF CARE, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.

5.2 YOU COVENANT NOT TO MAKE OR BRING ANY SUCH CLAIM AGAINST ANY RELEASEE.

## 6. INDEMNITY

YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS THE RELEASEES FROM AND AGAINST ANY AND ALL LOSSES, DAMAGES, LIABILITIES, DEFICIENCIES, CLAIMS, ACTIONS, JUDGMENTS, SETTLEMENTS, INTEREST, AWARDS, PENALTIES, FINES, COSTS, OR EXPENSES (INCLUDING REASONABLE LEGAL FEES) ARISING OUT OF OR RELATING TO (I) YOUR USE OF THE SERVICE; (II) YOUR BREACH OF THIS AGREEMENT; (III) YOUR VIOLATION OF ANY LAW OR THE RIGHTS OF ANY THIRD PARTY; OR (IV) ANY USER CONTENT OR MATERIALS SUBMITTED BY YOU.

## 7. PERSONAL PROPERTY

YOU ACKNOWLEDGE AND AGREE THAT SANCTUM ASSUMES NO RESPONSIBILITY FOR PERSONAL PROPERTY, REGARDLESS OF WHETHER LOST, STOLEN, OR DAMAGED, WHETHER AT A VENUE, DURING TRANSIT, OR OTHERWISE.

## 8. LIMITATION OF LIABILITY; LIABILITY CAP

8.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ANY RELEASEE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, OR BUSINESS INTERRUPTION.

8.2 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE RELEASEES’ TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (I) THE TOTAL AMOUNT PAID BY YOU TO SANCTUM IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM; AND (II) EUR 500.

8.3 NOTHING IN THIS AGREEMENT EXCLUDES OR LIMITS LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.

## PART 2: ADDITIONAL TERMS

## 9. ELIGIBILITY; ACCOUNT REGISTRATION; SECURITY

9.1 YOU MUST BE AT LEAST EIGHTEEN (18) YEARS OF AGE TO USE THE SERVICE UNLESS EXPRESSLY STATED OTHERWISE BY SANCTUM IN WRITING.

9.2 YOU AGREE TO PROVIDE TRUE, ACCURATE, CURRENT, AND COMPLETE INFORMATION WHEN CREATING AN ACCOUNT AND TO PROMPTLY UPDATE SUCH INFORMATION.

9.3 YOU ARE SOLELY RESPONSIBLE FOR ALL ACTIVITIES THAT OCCUR THROUGH YOUR ACCOUNT AND FOR MAINTAINING THE CONFIDENTIALITY OF YOUR LOGIN CREDENTIALS. YOU AGREE TO NOTIFY SANCTUM IMMEDIATELY OF ANY UNAUTHORISED USE OR SECURITY BREACH.

## 10. MEMBERSHIPS; SUBSCRIPTIONS; BILLING; NO REFUNDS

10.1 SANCTUM MAY OFFER SUBSCRIPTION-BASED ACCESS TO THE SERVICE. SUBSCRIPTIONS ARE BILLED ON A RECURRING BASIS AS SPECIFIED AT THE TIME OF PURCHASE (E.G., MONTHLY OR ANNUALLY) AND WILL CONTINUE UNTIL CANCELLED.

10.2 YOU MAY CANCEL YOUR SUBSCRIPTION AT ANY TIME; HOWEVER, EXCEPT WHERE REQUIRED BY APPLICABLE LAW, SUBSCRIPTIONS ARE NON-REFUNDABLE AND WE DO NOT PROVIDE CREDITS OR REFUNDS FOR PARTIALLY USED BILLING PERIODS.

10.3 SANCTUM RESERVES THE RIGHT TO CHANGE PRICING OR PLANS AT ANY TIME, AND WHERE REQUIRED BY LAW WILL PROVIDE NOTICE IN ADVANCE.

## 11. APPLE APP STORE AND GOOGLE PLAY TERMS CONTROL

IF YOU SUBSCRIBE OR MAKE PURCHASES THROUGH APPLE OR GOOGLE, YOU ACKNOWLEDGE AND AGREE THAT: (I) PAYMENT WILL BE CHARGED TO YOUR APPLE ID OR GOOGLE ACCOUNT; (II) SUBSCRIPTIONS AUTOMATICALLY RENEW UNLESS CANCELLED AT LEAST 24 HOURS BEFORE THE END OF THE CURRENT PERIOD; (III) YOU MUST MANAGE AND CANCEL SUBSCRIPTIONS THROUGH YOUR APP STORE SETTINGS; AND (IV) THE TERMS OF THE APPLICABLE APP STORE SHALL PREVAIL IN THE EVENT OF ANY CONFLICT WITH THIS AGREEMENT.

## 12. INTELLECTUAL PROPERTY; LICENSE RESTRICTIONS

12.1 ALL RIGHTS, TITLE, AND INTEREST IN AND TO THE SERVICE AND ALL CONTENT, SOFTWARE, TRADEMARKS, LOGOS, AUDIOVISUAL MATERIALS, AND OTHER MATERIALS (COLLECTIVELY, “MATERIALS”) ARE OWNED BY OR LICENSED TO SANCTUM AND ARE PROTECTED BY INTELLECTUAL PROPERTY LAWS.

12.2 YOU ARE GRANTED A LIMITED, NON-EXCLUSIVE, NON-TRANSFERABLE, REVOCABLE LICENSE TO ACCESS AND USE THE SERVICE FOR PERSONAL, NON-COMMERCIAL USE ONLY. YOU MAY NOT COPY, REPRODUCE, DISTRIBUTE, DISPLAY, SELL, SCRAPE, REVERSE ENGINEER, OR EXPLOIT ANY MATERIALS WITHOUT SANCTUM’S PRIOR WRITTEN CONSENT.

## 13. USER CONDUCT; COMMUNITY GUIDELINES

SANCTUM MAY, IN ITS SOLE DISCRETION, SUSPEND OR TERMINATE ACCESS FOR CONDUCT THAT IS UNLAWFUL, ABUSIVE, HARASSING, DISCRIMINATORY, THREATENING, OR OTHERWISE DISRUPTIVE OR HARMFUL TO OTHERS, STAFF, OR THE COMMUNITY.

## 14. CONTENT CAPTURE; CONSENT

BY PARTICIPATING IN SANCTUM EXPERIENCES, YOU GRANT SANCTUM A WORLDWIDE, ROYALTY-FREE, PERPETUAL LICENSE TO USE PHOTOGRAPHS, VIDEO, OR AUDIO CAPTURED DURING SUCH EXPERIENCES FOR LAWFUL BUSINESS AND PROMOTIONAL PURPOSES, UNLESS YOU OPT OUT IN WRITING PRIOR TO CAPTURE WHERE REASONABLY PRACTICABLE.

## 15. MODIFICATION; DISCONTINUATION; FORCE MAJEURE

15.1 SANCTUM RESERVES THE RIGHT TO MODIFY, EDIT, DELETE, SUSPEND, OR DISCONTINUE THE SERVICE (OR ANY PORTION THEREOF) AT ANY TIME, WITH OR WITHOUT NOTICE.

15.2 SANCTUM SHALL NOT BE LIABLE FOR ANY FAILURE OR DELAY CAUSED BY EVENTS BEYOND ITS REASONABLE CONTROL, INCLUDING TECHNICAL OUTAGES, VENUE CLOSURES, NATURAL EVENTS, PANDEMICS, OR GOVERNMENTAL ACTIONS.

## 16. GOVERNING LAW; JURISDICTION; CONSUMER RIGHTS

16.1 THIS AGREEMENT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE NETHERLANDS, WITHOUT REGARD TO CONFLICT-OF-LAWS PRINCIPLES.

16.2 TO THE MAXIMUM EXTENT PERMITTED BY LAW, ANY DISPUTE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERVICE SHALL BE BROUGHT EXCLUSIVELY IN THE COMPETENT COURTS OF AMSTERDAM, THE NETHERLANDS.

16.3 NOTHING IN THIS AGREEMENT LIMITS ANY MANDATORY CONSUMER RIGHTS YOU MAY HAVE UNDER APPLICABLE LOCAL LAW THAT CANNOT BE EXCLUDED OR WAIVED.

## 17. MISCELLANEOUS

17.1 ENTIRE AGREEMENT. THIS AGREEMENT CONSTITUTES THE ENTIRE AGREEMENT BETWEEN YOU AND SANCTUM REGARDING THE SUBJECT MATTER AND SUPERSEDES ALL PRIOR OR CONTEMPORANEOUS UNDERSTANDINGS.

17.2 SEVERABILITY. IF ANY PROVISION IS HELD INVALID, ILLEGAL, OR UNENFORCEABLE, THE REMAINING PROVISIONS SHALL REMAIN IN FULL FORCE.

17.3 ASSIGNMENT. SANCTUM MAY ASSIGN THIS AGREEMENT WITHOUT RESTRICTION. YOU MAY NOT ASSIGN THIS AGREEMENT WITHOUT SANCTUM’S PRIOR WRITTEN CONSENT.

17.4 LANGUAGE. THE PARTIES HAVE REQUIRED THAT THIS AGREEMENT AND ALL DOCUMENTS RELATED TO IT BE DRAWN UP IN ENGLISH.

CONTACTING SANCTUM: FOR QUESTIONS, COMMENTS, OR CLAIMS REGARDING THE SERVICE, CONTACT: HELLO@WEARESANCTUM.COM.`;

export const privacy = `THIS PRIVACY POLICY (THIS “POLICY”) DESCRIBES HOW AND WHEN SANCTUM B.V., A PRIVATE LIMITED LIABILITY COMPANY INCORPORATED UNDER THE LAWS OF THE NETHERLANDS, WITH ITS REGISTERED OFFICE AT SINGEL 174A, 1016 AJ AMSTERDAM, THE NETHERLANDS (“SANCTUM,” “WE,” OR “US”), COLLECTS, USES, STORES, AND DISCLOSES INFORMATION WHEN YOU USE OUR WEBSITE(S), OUR MOBILE APPLICATION(S) AND RELATED DIGITAL PLATFORMS (THE “APP”), AND OUR IN-PERSON AND DIGITAL SERVICES (COLLECTIVELY, TOGETHER WITH THE WEBSITE AND APP, THE “SERVICE”).

BY USING THE SERVICE, YOU CONSENT TO THE COLLECTION, USE, AND DISCLOSURE OF INFORMATION IN ACCORDANCE WITH THIS POLICY, SUBJECT TO YOUR RIGHTS UNDER APPLICABLE LAW.

## 1. DEFINITIONS

“PERSONAL DATA” (OR “PERSONAL INFORMATION”) MEANS INFORMATION THAT IDENTIFIES, RELATES TO, DESCRIBES, OR COULD REASONABLY BE LINKED TO AN IDENTIFIED OR IDENTIFIABLE INDIVIDUAL. IT DOES NOT INCLUDE AGGREGATED OR DE-IDENTIFIED INFORMATION.

## 2. INFORMATION WE COLLECT

WE MAY COLLECT PERSONAL DATA IN THE FOLLOWING CATEGORIES:

(A) INFORMATION YOU PROVIDE VOLUNTARILY, INCLUDING NAME, EMAIL ADDRESS, TELEPHONE NUMBER, BILLING INFORMATION, ACCOUNT DETAILS, AND CORRESPONDENCE.

(B) INFORMATION COLLECTED THROUGH YOUR USE OF THE SERVICE, INCLUDING DEVICE INFORMATION, IP ADDRESS, APP/WEBSITE USAGE DATA, LOG DATA, COOKIE DATA, AND ANALYTICS INFORMATION.

(C) TRANSACTION INFORMATION, INCLUDING PURCHASE HISTORY AND SUBSCRIPTION STATUS (PAYMENTS ARE PROCESSED BY THIRD-PARTY PROVIDERS; WE DO NOT STORE FULL PAYMENT CARD DETAILS).

(D) MEDIA CONTENT, INCLUDING PHOTOGRAPHS, AUDIO, OR VIDEO RECORDED AT EXPERIENCES WHERE PERMITTED.

(E) HEALTH-RELATED INFORMATION ONLY IF YOU VOLUNTARILY DISCLOSE IT (E.G., TO INFORM FACILITATORS OF RELEVANT CONDITIONS). WE DO NOT REQUEST OR REQUIRE MEDICAL DATA AS A CONDITION OF USE UNLESS NECESSARY FOR SAFETY OR LEGAL COMPLIANCE.

## 3. HOW WE USE PERSONAL DATA

WE USE PERSONAL DATA FOR PURPOSES INCLUDING:

- PROVIDING, OPERATING, AND IMPROVING THE SERVICE;
- MANAGING BOOKINGS, ACCOUNTS, AND SUBSCRIPTIONS;
- PROCESSING TRANSACTIONS AND CUSTOMER SUPPORT;
- COMMUNICATING SERVICE UPDATES, ADMINISTRATIVE NOTICES, AND RELEVANT INFORMATION;
- ENSURING SAFETY, SECURITY, FRAUD PREVENTION, AND POLICY ENFORCEMENT;
- COMPLYING WITH LEGAL AND REGULATORY OBLIGATIONS.

WE DO NOT SELL PERSONAL DATA.

## 4. LEGAL BASES (WHERE APPLICABLE)

WHERE REQUIRED (INCLUDING UNDER GDPR), WE PROCESS PERSONAL DATA ON THE BASIS OF ONE OR MORE OF THE FOLLOWING: CONTRACTUAL NECESSITY; LEGITIMATE INTERESTS; LEGAL OBLIGATION; AND/OR YOUR CONSENT.

## 5. HOW WE SHARE PERSONAL DATA

WE MAY DISCLOSE PERSONAL DATA TO:

- SERVICE PROVIDERS (E.G., HOSTING, ANALYTICS, CUSTOMER SUPPORT, PAYMENT PROCESSORS);
- TECHNOLOGY PARTNERS (E.G., APP DISTRIBUTION PLATFORMS SUCH AS APPLE AND GOOGLE);
- PROFESSIONAL ADVISERS (E.G., LEGAL, ACCOUNTING, INSURANCE);
- AUTHORITIES OR THIRD PARTIES WHERE REQUIRED BY LAW OR TO PROTECT RIGHTS, SAFETY, AND SECURITY.

WE REQUIRE THIRD-PARTY SERVICE PROVIDERS TO PROCESS PERSONAL DATA ONLY AS NECESSARY TO PERFORM SERVICES FOR US AND TO IMPLEMENT APPROPRIATE SAFEGUARDS.

## 6. COOKIES AND ANALYTICS

WE MAY USE COOKIES, SDKS, PIXELS, LOG FILES, AND SIMILAR TECHNOLOGIES TO COLLECT INFORMATION ABOUT HOW THE SERVICE IS USED, TO OPERATE AND IMPROVE THE SERVICE, AND TO MEASURE PERFORMANCE. YOU MAY CONTROL COOKIES THROUGH YOUR BROWSER SETTINGS, SUBJECT TO TECHNICAL LIMITATIONS.

## 7. INTERNATIONAL TRANSFERS

AS A GLOBAL BUSINESS, YOUR PERSONAL DATA MAY BE TRANSFERRED TO AND PROCESSED IN COUNTRIES OTHER THAN YOUR COUNTRY OF RESIDENCE. WHERE REQUIRED BY LAW, WE IMPLEMENT APPROPRIATE SAFEGUARDS FOR SUCH TRANSFERS.

## 8. DATA RETENTION

WE RETAIN PERSONAL DATA ONLY FOR AS LONG AS NECESSARY FOR THE PURPOSES DESCRIBED IN THIS POLICY AND/OR AS REQUIRED BY APPLICABLE LAW, INCLUDING TAX, ACCOUNTING, AND LEGAL REQUIREMENTS.

## 9. YOUR RIGHTS

SUBJECT TO APPLICABLE LAW, YOU MAY HAVE RIGHTS INCLUDING THE RIGHT TO ACCESS, CORRECT, DELETE, RESTRICT, OR OBJECT TO PROCESSING, AND TO WITHDRAW CONSENT WHERE PROCESSING IS BASED ON CONSENT. TO EXERCISE RIGHTS, CONTACT US AS SET OUT BELOW.

## 10. SECURITY

WE USE REASONABLE ADMINISTRATIVE, TECHNICAL, AND PHYSICAL SAFEGUARDS DESIGNED TO PROTECT PERSONAL DATA. HOWEVER, NO SECURITY MEASURES CAN BE GUARANTEED TO BE 100% EFFECTIVE, AND YOU USE THE SERVICE AT YOUR OWN RISK.

## 11. CHILDREN

THE SERVICE IS NOT INTENDED FOR CHILDREN UNDER 18 UNLESS EXPRESSLY STATED. WE DO NOT KNOWINGLY COLLECT PERSONAL DATA FROM CHILDREN WITHOUT VERIFIED PARENTAL CONSENT WHERE REQUIRED.

## 12. UPDATES TO THIS POLICY

WE MAY UPDATE THIS POLICY FROM TIME TO TIME. WHEN WE DO, WE WILL REVISE THE “LAST UPDATED” DATE ABOVE. YOUR CONTINUED USE OF THE SERVICE AFTER SUCH CHANGES CONSTITUTES ACCEPTANCE OF THE UPDATED POLICY, SUBJECT TO YOUR RIGHTS UNDER APPLICABLE LAW.

## 13. CONTACTING US

IF YOU HAVE QUESTIONS OR REQUESTS ABOUT THIS POLICY, CONTACT: HELLO@WEARESANCTUM.COM OR BY POST AT: SANCTUM B.V., SINGEL 174A, 1016 AJ AMSTERDAM, THE NETHERLANDS.`;
