// Content for Press, Careers and Academy — taken from wearesanctum.com (press-partners, careers, academy).
const C = 'https://cdn.prod.website-files.com/6924318a2ed5d4cd56895681/';
const P = 'https://cdn.prod.website-files.com/6924318a2ed5d4cd56895688/';

export const press = [
  { pub: 'British Vogue', title: 'I’ve Seen The Future Of Wellness', date: 'January 21, 2023', url: 'https://www.vogue.co.uk/beauty/article/sanctum', img: P + '6924318a2ed5d4cd5689593e_vertical_0001_britishvogue.jpg' },
  { pub: 'The Sunday Times', title: 'Inside Sanctum, the hot new fitness class that will make you cry', date: 'March 6, 2023', url: 'https://www.thetimes.co.uk/article/inside-sanctum-the-hot-new-fitness-class-that-will-make-you-cry-0w37f3l2j', img: P + '6924318a2ed5d4cd56895b00__methode_sundaytimes_prod_web_bin_86efb50a-abbb-11ed-bde0-64a2ad0fcf88.jpeg' },
  { pub: 'American Vogue', title: 'I Survived My First Wellness Festival', date: 'November 24, 2022', url: 'https://www.vogue.com/article/i-survived-my-first-wellness-festival', img: P + '6924318a2ed5d4cd56895969_square_0000_vogue.jpg' },
  { pub: 'BBC', title: 'In Pursuit of Wellness series: Dancing towards happiness', date: 'November 15, 2022', url: 'https://www.bbc.com/storyworks/in-pursuit-of-wellness/dancing-towards-happiness', img: P + '6924318a2ed5d4cd56895a2a_Screenshot%202023-02-14%20at%2009.28.54.png' },
  { pub: 'Goop', title: 'Epic workouts, cold plunges & kundalini yoga at Six Senses', date: '', url: 'https://goop.com/travel/experiences/alma-wellness-festival-at-six-senses-ibiza/', img: P + '6924318a2ed5d4cd56895b17_2C8A1129.jpg' },
  { pub: 'Grazia', title: 'Mindful movement community Sanctum comes to Dubai', date: 'February 5, 2023', url: 'https://graziamagazine.com/me/articles/mindful-wellness-movement-sanctum-dubai/', img: P + '6924318a2ed5d4cd56895953_square_0002_grazia.jpg' },
  { pub: 'Harper’s Bazaar Arabia', title: 'Memos From The Middle East', date: 'February 3, 2023', url: 'https://www.harpersbazaararabia.com/hbanews/memos-from-the-middle-east-3', img: P + '6924318a2ed5d4cd56895ad4_63e3a32d30772faf03585c83_vertical_0003_harpersbazaar.jpeg' },
  { pub: 'TimeOut', title: 'Amsterdam’s popular wellness-workout classes Sanctum hit the UAE', date: 'January 20, 2023', url: 'https://www.timeoutdubai.com/news/sanctum-workout-classes-launch-in-uae', img: P + '6924318a2ed5d4cd56895b7d_ACG_1544.jpg' },
  { pub: 'Arabian Business', title: 'UAE’s first Sanctum awakening retreat to take place in Abu Dhabi', date: 'January 20, 2023', url: 'https://www.arabianbusiness.com/lifestyle/health-fitness/uaes-first-sanctum-awakening-retreat-to-take-place-in-abu-dhabi', img: P + '6924318a2ed5d4cd5689597e_square_0001_arabian.jpg' },
  { pub: 'New York Post', title: 'How Ibiza went from a party island to a crunchy wellness destination', date: 'December 3, 2022', url: 'https://nypost.com/2022/12/03/infamous-party-island-ibiza-is-now-a-wellness-destination/', img: P + '6924318a2ed5d4cd568959df_vertical_0002_newyork.jpg' },
  { pub: 'A Hotel Life', title: 'Souvenirs From Alma at Six Senses Ibiza', date: 'November 24, 2022', url: 'https://www.ahotellife.com/souvenirs-from-alma-at-six-senses-ibiza/', img: P + '6924318a2ed5d4cd56895928_ahotellife.webp' },
  { pub: 'ELLE', title: 'Hotspots: Even ontspannen: de 6 fijnste retreats in Europa', date: 'July 7, 2022', url: 'https://www.elle.com/nl/eten/elle-eten-hotspots/g40530652/retreats-europa/', img: P + '6924318a2ed5d4cd56895996_elle.jpeg' },
  { pub: 'WINK', title: 'Happy couple Luuk & Gabriel', date: 'March 6, 2023', url: 'https://cdn.prod.website-files.com/63ad60bbda54a218280fd9c7/6405cda9cc45a7161a9529e5_060-317%20S%20Happy%20Couple%20v1.pdf', img: P + '6924318a2ed5d4cd56895aea_Schermafbeelding%202023-03-06%20om%2012.25.06.png' },
  { pub: 'Stylist UK', title: 'Can an exercise class expand your mind?', date: '', url: '', img: P + '6924318a2ed5d4cd56895bac_IMG_4016.jpeg' },
  { pub: 'Woman DE', title: 'Let’s get moving', date: '', url: '', img: P + '6924318a2ed5d4cd56895c29_Screenshot%202023-05-17%20at%2013.03.53.png' },
];

export const roles = [
  {
    title: 'European Operations Manager',
    facts: [['Location', 'London, UK / Amsterdam, Netherlands'], ['Reports to', 'Head of Operations and Partnerships'], ['Salary', '£45k to £50k (an equivalent salary will be offered in the local currency, aligned with market conditions)']],
    body: ['The European Operations Manager is responsible for the operational performance and commercial growth of their region, ensuring every market delivers exceptional client experiences whilst building engaged communities and sustainably growing attendance.', 'This role owns market performance, commercial partnerships, operational planning and team leadership, ensuring every market consistently delivers exceptional experiences while achieving commercial objectives.', 'The European Operations Manager leads the Local Operations Supervisors, supports operational excellence across all markets and drives continuous improvement.'],
    jd: C.replace('6924318a2ed5d4cd56895681/', '6924318a2ed5d4cd56895681/') + '6ac4db11b5a46b84067643bb_Job%20Description_%20European%20Operations%20Manager.pdf',
    email: 'kat@wearesanctum.com', apply: 'mailto:kat@wearesanctum.com?subject=European%20Area%20Manager',
  },
  {
    title: 'Digital Product & Growth Manager',
    facts: [['Location', 'London, UK / Amsterdam, Netherlands / Dubai, UAE'], ['Reports to', 'Head of Marketing'], ['Employment type', 'Full time'], ['Salary', '£38,000 to £45,000 (an equivalent salary will be offered in the local currency, aligned with market conditions)'], ['Performance bonus', 'Up to 5 to 20% annual performance bonus based on agreed business and product KPIs']],
    body: ['The Digital Product & Growth Manager is responsible for defining, evolving and growing Sanctum Digital App worldwide.', 'This role leads Sanctum’s digital product strategy, member experience and subscription growth, ensuring the platform continues to deliver an exceptional experience whilst enabling Sanctum Digital to scale sustainably.', 'Working closely with the Marketing, Content, Operations and Leadership Teams, the Digital Product & Growth Manager oversees the evolution of Sanctum Digital, manages the product roadmap and defines the systems, priorities and optimisation frameworks that drive member engagement, retention and recurring revenue.', 'Whilst maintaining the day-to-day excellence of the platform, this role is equally responsible for designing the future of Sanctum Digital, creating scalable product, growth and optimisation models that support international expansion and establish Sanctum Digital as one of the world’s leading digital wellbeing platforms.'],
    focus: { intro: 'The Digital Product & Growth Manager balances the needs of today’s business with the long-term development of Sanctum Digital App. Approximately 60% of the role focuses on current operations, including:', list: ['Product roadmap management', 'Product optimisation', 'User experience', 'Product releases and quality assurance', 'Content publishing', 'Customer feedback', 'Product analytics', 'External technology partner management'], outro: 'Approximately 40% of the role focuses on building the next stage of Sanctum Digital’s growth, developing the systems, products and commercial opportunities required to scale the platform internationally over the next 12 to 18 months and beyond.' },
    email: 'careers@wearesanctum.com', apply: 'mailto:gab@wearesanctum.com?subject=Digital%20Product%20%26%20Growth%20Manager',
  },
  {
    title: 'Sanctum Experience Host',
    facts: [['Location', 'London, UK / Amsterdam, Netherlands'], ['Reports to', 'Local Operations Supervisor'], ['Employment type', 'Freelance, part time']],
    body: ['The Sanctum Experience Host is responsible for bringing every Sanctum experience to life.', 'More than a Front of House role, you are the first and last impression of every class. You create an environment where clients feel welcomed, connected and cared for from the moment they arrive until long after they leave.', 'You are responsible for ensuring every experience runs seamlessly, supporting the Guide, maintaining exceptional operational standards and helping build a thriving Sanctum community within your local market.', 'This role is perfect for someone who genuinely loves Sanctum. We are looking for people who believe in the experience, naturally connect with others and want to play an active role in growing our community.'],
    email: 'london@wearesanctum.com or amsterdam@wearesanctum.com', apply: 'mailto:london@wearesanctum.com?subject=Sanctum%20Experience%20Host%20Role',
  },
];

export const careersImg = { hero: C + '6924318a2ed5d4cd568959fe_GLD_7633%201%20(1).webp', a: C + '6924318a2ed5d4cd5689594c_DSC08124%20-%20LR.webp', b: C + '6924318a2ed5d4cd56895999_IMG_0201%20copy.webp', c: C + '6924318a2ed5d4cd56895947_ACG_1380%201.webp' };

export const academy = {
  hero: C + '6924318a2ed5d4cd56895a6c_GLD_1731_LQ.webp',
  imgs: [C + '6924318a2ed5d4cd568959bd_GLD_2997%202.webp', C + '6924318a2ed5d4cd5689594c_DSC08124%20-%20LR.webp', C + '6924318a2ed5d4cd56895999_IMG_0201%20copy.webp', C + '6924318a2ed5d4cd56895947_ACG_1380%201.webp'],
  intro: 'The Sanctum Academy recruits talent globally and conducts a thorough training program to those who want to pursue a career as a Sanctum guide.',
  about: 'The Sanctum Academy is a complete tutorial process from the moment you apply to join the Academy. Led by the founder, Luuk Melisse, the Academy will guide you through practical workshops to become a guide. The Sanctum Bible encloses the inner workings of the class structure, the methods, theory and psychology behind the Sanctum experiences. On successful completion of the Academy you will have access to the Sanctum Platform, which continues your development as a guide with scientific knowledge, movement inspiration, music curation, brand updates and business possibilities.',
  guide: 'Creative storytelling is the Sanctum DNA, and moving confidently to the rhythm of the music is essential. A Sanctum guide is a natural performer who thrives in front of a crowd, enthusiastic to inspire others and create authentic experience. A Sanctum guide understands the power of shared experience, is curious about exploration of human energy frequencies and the power of enabling connection within a group.',
  apply: 'https://je5d7snmjng.typeform.com/to/wTaN6RYM',
  login: 'https://www.wearesanctum.nl/',
  guides: [
    { name: 'Luuk', est: 2019, img: C + '6924318a2ed5d4cd56895a4a_Luuk%201%20(4)%20(1).webp', img2: C + '6924318a2ed5d4cd56895a48_Luuk%202%20(1)%20(1).webp', ig: 'https://www.instagram.com/luukmelisse/', quote: 'I believe in the power of your energy. Your unique energy, or frequency, is the most powerful source which is expressed through thoughts, movement and actions. It reflects who you are at this very moment. Energy is motion and is always changing, and the good news is that you can change your own energy by the same thoughts, movements and actions. I’m here to guide you to elevate your frequency.', facts: [['Nationality', 'Dutch'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Scorpio'], ['Background', 'Dance, sports, theatre'], ['Key quality', 'Inspiring, vulnerable']] },
    { name: 'Michelle', est: 2019, img: C + '6924318a2ed5d4cd56895a32_Michelle%201%20(2).webp', img2: C + '6924318a2ed5d4cd56895a2f_Michelle%202%20(1).webp', quote: 'I believe in embracing any contradiction, within the world and within ourselves. It is the starting point of listening, understanding, and growth. From me, you can expect a journey of self-discovery where we don’t take ourselves too seriously and at the same time overcome obstacles through empowering music and speech.', facts: [['Nationality', 'Dutch'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Leo'], ['Background', 'Performing arts, fitness'], ['Key quality', 'Caring, inspiring, edgy']] },
    { name: 'Larissa', est: 2020, img: C + '6924318a2ed5d4cd56895a2e_Larissa%201%20(1).webp', img2: C + '6924318a2ed5d4cd56895a30_Larissa%202.webp', quote: 'I believe in the power of body-mind connection. Our body remembers, knows and sees what our mind purposely forgets. It is through movement and breath work that we can let these two entities communicate.', facts: [['Nationality', 'Dutch'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Aquarius and Aquarius rising'], ['Background', 'Psychology, body-oriented therapy, breath work and meditation'], ['Key qualities', 'Warmth, attentive, spiritual']] },
    { name: 'Jack', est: 2022, img: C + '6924318a2ed5d4cd56895a1d_Jack%201.webp', img2: C + '6924318a2ed5d4cd56895a1e_Jack%202%20(1).webp', quote: 'You can drown in a puddle or you can drown in a pool. Everyone has their own struggles and needs a place to share them.', facts: [['Nationality', 'Dutch'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Aquarius, with Pisces sun'], ['Background', 'Social worker born and raised in Amsterdam'], ['Key quality', 'Open and understanding to people from all walks of life']] },
    { name: 'Cassie', est: 2022, img: C + '6924318a2ed5d4cd56895a2d_Cassie%201%20(1).webp', img2: C + '6924318a2ed5d4cd56895a2c_Cassie%202%20(1).webp', quote: 'I believe in making the most out of all situations; the good, the bad, the excellent and the ugly, and using life experience as a powerful tool for relatability and connection.', facts: [['Nationality', 'British'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Libra'], ['Background', 'PR & events, fitness, wellbeing concept development'], ['Key quality', 'Open, honest and fearless']] },
    { name: 'Meg', est: 2022, img: C + '6924318a2ed5d4cd56895a49_Meg%201.webp', img2: C + '6924318a2ed5d4cd56895a31_Meg%202%20(1).webp', quote: 'I believe in the wisdom of love and the love of wisdom. We are all here to share this journey of self-actualization, supporting each other as a Big Team. From me, you can expect full presence, unconditional support and authenticity.', facts: [['Nationality', 'Italian'], ['Homebase', 'Amsterdam'], ['Star sign', 'Virgo'], ['Background', 'Acting, performing arts, breathwork'], ['Key quality', 'Commitment, catharsis, self-expression']] },
    { name: 'Yves', est: 2022, img: C + '6924318a2ed5d4cd56895a4b_Yves%201%20(1).webp', img2: C + '6924318a2ed5d4cd56895a4c_Yves%202%20(1).webp', quote: 'I believe in the power of curiosity. Curious of our experience, of our exploration. The dark and the light. I am open with you, I am vulnerable with you, I am connected to you. As a community we grow together.', facts: [['Nationality', 'New Zealander'], ['Homebase', 'Amsterdam'], ['Horoscope', 'Aquarius'], ['Background', 'Performing arts, fitness, commercial business'], ['Key quality', 'Energetic presence, kindness']] },
  ],
  gallery: [C + '6924318a2ed5d4cd56895997_0D1A5416%201.webp', C + '6924318a2ed5d4cd568959a3_0D1A4947%201.webp', C + '6924318a2ed5d4cd568959a0_0D1A4536%201.webp', C + '6924318a2ed5d4cd5689599c_0D1A5633%201.webp'],
};
